 language: scala
 scala:
   - "2.10.1"
 
 jdk:
   - oraclejdk7
   - openjdk7
   
notifications:
    email:
       recipients:
        - vidyac.raghav@gmail.com 
        - vidya@shippable.com
        on_success: change
        on_failure: always
